### ISSUE TITLE
phonesystem:phonesystem

### ISSUE THREAD

**Issue by tonyrking** [izer-xyz/3cx-docker#13]
Synology DS920+ / DSM7.1

Does the system need a user 'phonesystem' I created one with R/W access to the Docker storage just in case.. stuck!
Totally loving the idea of having this in Docker instead of running a whole VM. Thanks for all the effort!

![New Note](https://user-images.githubusercontent.com/59649152/187797095-de11d0f2-bb1b-4900-ab37-71e48ab661ea.jpeg)

**Comment by sinegar** [comment]
The `phonesystem` user is not required. `chwon` is handling an edge case when the container is restarted. I have _fixed_ (ignore the display) it in the latest test release as it was confusing. 

Your issue is with `systemd`. Either not mounting `cgroup` or not having the right version (v1). 

Can you check [Troubleshooting 1)](https://github.com/izer-xyz/3cx-docker#troubleshooting):

```
 $ docker run -it --rm --tmpfs /run --tmpfs /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro izerxyz/3cx:latest /lib/systemd/systemd --log-level=debug --log-target=console --show-status=true
```

**Comment by sinegar** [comment]
Closing all issues before archiving the project.
