### ISSUE TITLE
Livechat audio call silent

### ISSUE THREAD

**Issue by jonatan-holmgren** [izer-xyz/3cx-docker#18]
My livechat on my website works fine, but when someone escalates it to a call both sides simply hear nothing. What steps are there to debug? Any other ports I would need to open?

**Comment by sinegar** [comment]
The web call uses WebRTC and you are going through multiple firewalls (VM, host, …) debugging will be fun. 

The 3cx port list is a good starting point https://www.3cx.com/docs/ports/ . 

The other thing to try is the firewall checker (https://www.3cx.com/docs/firewall-checker/) but keep in mind that it will fail (I think due to docker port mapping). Maybe try host networking to avoid port mapping. 

There is also #12 with some info but not resolved. As I noted on the other issue I don’t use the web call feature.

**Comment by sinegar** [comment]
Closing all issues before archiving the project.
