### ISSUE TITLE
Restoring a previous backup with 3cx-docker

### ISSUE THREAD

**Issue by Mickeyr61** [izer-xyz/3cx-docker#20]
Finally I got the izer-xyz up-and-running. First it didn't start with the 

Failed to create /init.scope control group: Read-only file system
Failed to allocate manager object: Read-only file system
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...

Error message. Which I was able to correct with the following command:

docker run --detach --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:rw --cgroupns=host ghcr.io/izer-xyz/3cx:latest

Now 3CX started and I was able to connect to the webinterface. Unfortunately I could not do a restore from a previous backup. It gives the message below:

The backup version 18.0.7.312 is newer than the PBX version 18.0.5.418. You can restore this backup only with PBX version 18.0.7.312 or newer.

Is there any way to update the 3CX from the command line, instead of building a new image?

**Comment by sinegar** [comment]
The recent images for x64 are available as testing (https://github.com/izer-xyz/3cx-docker/releases). Example: 

`docker run ghcr.io/izer-xyz/3cx:18.0.7.312-test`

Or you could try `apt update` and the `apt upgrade` in an attached console but I have never tried. 

The `latest` docker tag has not changed version since 18.0.5.418 as it was the last version with arm support (which I use).

**Comment by Mickeyr61** [comment]
Thanks for the prompt reply! It worked. This is what I did:
- connecting to the docker container 
- run a apt update and a apt-upgrade (which found the latest version)
- running a cleanup, and restarted the container

**Comment by sinegar** [comment]
I am glad it worked.

However, the container state is not persistent. It should survive a host reboot but if I recall well container stop/start may cause a reset. Don’t forget to setup an auto backup to a persistent volume.
